# Generated by Django 3.0.8 on 2020-07-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='estate',
            new_name='city',
        ),
    ]
